title: Daniel Dominguete # your name (or website title) here
logo: "/images/daniel_logo_270x270.png?raw=true"
description: >
  <h3>About</h3>
  <p>
  Entrepreneurial spirited and proactive executive, my goal is to improve business results with innovation and technology-focused on creating value for shareholders and customers.
  15+ years of experience inside & working with startups and large corporations on their technical and business challenges.
  With strong knowledge in the fields of Machine Learning (Artificial Intelligence), Marketing & Sales, Engineering and Information Technology, I continually seek to learn and apply new concepts and tools of management, design, implementation and lifecycle management for innovative solutions.
  </p>
  <h3>Contacts</h3>
  <p>
  <a href="https://www.linkedin.com/in/dominguete/" target="_blank"><img border="0" alt="Linkedin" src="/images/Linkedin-icon.png" width="32" height="32"></a>
  <a href="https://www.facebook.com/daniel.dominguete" target="_blank"><img border="0" alt="Facebook" src="/images/Facebook-icon.png" width="32" height="32"></a>
  <a href="mailto:daniel.dominguete@gmail.com" target="_blank"><img border="0" alt="Facebook" src="/images/Gmail-icon.png" width="32" height="32"></a>
  <a href="https://medium.com/@daniel.dominguete" target="_blank"><img border="0" alt="Medium" src="/images/LiveJournal-icon.png" width="32" height="32"></a>
  <a href="https://www.youtube.com/user/dominguete/" target="_blank"><img border="0" alt="Facebook" src="/images/Youtube-icon.png" width="32" height="32"></a>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-174926075-1
