title: Daniel Dominguete, M.Sc. # your name (or website title) here
logo: "images/dominguete_executive_270x270.png?raw=true"
description: >
  <h3>About</h3>
  <p>
  18+ years of experience of technical and business IT challenges.
  </p>
  <h3>Core Competences</h3>
  <p> Data Analytics | Machine Learning |  Business Intelligence | Marketing & Business Development</p>
  <h3>Contacts</h3>
  <p>
  <a href="https://www.linkedin.com/in/dominguete/" target="_blank"><img border="0" alt="Linkedin" src="/images/linkedin.png" width="32" height="32"></a>
  <a href="mailto:daniel.dominguete@gmail.com" target="_blank"><img border="0" alt="Gmail" src="/images/gmail.png" width="32" height="32"></a>
  <a href="https://medium.com/@daniel.dominguete" target="_blank"><img border="0" alt="Medium" src="/images/medium.png" width="32" height="32"></a>
  <a href="https://github.com/danieldominguete" target="_blank"><img border="0" alt="Github" src="/images/git.png" width="32" height="32"></a>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-174926075-1
