title: Daniel Dominguete # your name (or website title) here
logo: "/images/daniel_logo_270x270.png?raw=true"
description: >
  <h2>Professional Portfolio</h2>
  <p>Contacts</p>
  <p>
  <a href="https://www.linkedin.com/in/dominguete/"><img border="0" alt="Linkedin" src="/images/Linkedin-icon.png" width="32" height="32"></a>
  <a href="https://www.linkedin.com/in/dominguete/"><img border="0" alt="Linkedin" src="/images/Linkedin-icon.png" width="32" height="32"></a>
  <a href="https://www.linkedin.com/in/dominguete/"><img border="0" alt="Linkedin" src="/images/Linkedin-icon.png" width="32" height="32"></a>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
